### PR TITLE
Open submission in browser if user confirms

### PR DESCRIPTION
**Pull request by tyilo**
This doesn't actually work unless the user has at least one of the following two lines in their `~/.kattisrc`:

```
[kattis]
hostname: open.kattis.com
submissionsurl: https://open.kattis.com/submissions/
```

Shouldn't kattis open provide the `hostname` in https://open.kattis.com/download/kattisrc ?

### CODE REVIEW

**Comment by niemela** [comment]
> Shouldn't kattis open provide the hostname in https://open.kattis.com/download/kattisrc ?

Did we provide that before? (@gkreitz, @austrin )

**Comment by jsannemo** [comment]
We haven't done so for as long as I can remember (for at least a year or two). However, it seems like a reasonable thing to add. The second option (submissionsurl) follows more what we do currently (i.e. avoid to hard code actual the URL path into the client).

**Comment by gkreitz** [comment]
The hostname field in kattisrc is (really old) legacy, IIRC, so that won't be present in anything new. As @jsannemo says, the preferable way would be for us to add submissionsurl to the config files we generate.

Regardless of what we do, there will be a lot of config files where this PR would prompt, and then throw an exception if the user selects Yes, so I think this PR should only prompt to open in a web browser if the appropriate field is in the config file.

**Comment by mikaelgoldmann** [comment]
Somewhat related, should we do something about the fact that the config
file ties the submit script to a specific site?

**Comment by niemela** [comment]
> Somewhat related, should we do something about the fact that the config
> file ties the submit script to a specific site?

The way things currently work (with Kattis) it kinda have to.

**Comment by tyilo** [comment]
Any updates on what should be done to the kattisrc or the script to get merged?

**Comment by niemela** [comment]
The comment from @gkreitz (https://github.com/Kattis/kattis-cli/pull/2#issuecomment-168635283) should be fixed. Also, is has to be rebased.

**Pull request closed without merging**
