### PR TITLE
Avoid SNI issues by enforcing python 3

### LINKED ISSUE #10: Missing SSL support in python2 breaks the script
Easiest fix is probably to make it python3 only. With python2, the user needs to go to some effort to make it work. At least on Mac and Ubuntu 14.04 it doesn't work out of the box with python2.

Workarounds:
- Depending on your setup, this might not be a problem for you
- You can try running the script using python3

### PR DESCRIPTION
**Pull request by mikaelgoldmann**
Fixes #10

Since the python 2 support for SNI appears to be shakey at best on
several platforms, the script is actually easier to use if we make
it python 3 only.

### CODE REVIEW

**Comment by mikaelgoldmann** [comment]
@pehrsoderman @austrin This seems like an easy way to make the script work well with cloudflare.

**Comment by austrin** [comment]
@mikaelgoldmann trying to understand the options here.  Which subset of the following statements are correct?
1. The issue is only for Python versions before 2.7.9 (https://stackoverflow.com/a/31734012).
2. The issue is only with the requests lib, so one possibility would be to go back to using urllib.
3. The issue can be resolved by installing some appropriate set of additional dependencies (https://stackoverflow.com/a/18579484).

If the first statement is correct I don't think we should change anything.  2.7.9 is almost 1.5 years old, I'm not sure anyone but a Ubuntu LTS user will have an older version at this point, and that will resolve itself with the imminent release of 16.04.

If first statement is not correct but some of the other two are correct it is a bit less clear.

PS in case you are not aware, you can only assign one person to an issue.

**Comment by mikaelgoldmann** [comment]
@austrin I'm pretty sure 2 is false - I did some limited testing. I haven't tried all versions of 1 and 3, but my mac has python 2.7.10 and it's still a problem. I don't think 3 is viable for most users.

**Comment by mikaelgoldmann** [comment]
@austrin so, basically,
1. is false since my Mac has a newer version and still doesn't work
2. is false since I tried accessing open.kattis.com using urllib2 (well, rather than urllib) and that failed
3. will no doubt work, though I don't know exactly what is actually needed

Basically, I think anyone who can get 3 to work is more than qualified to port the script back to python 2 if that is what they want.

I'd rather rely on platforms having python 3 than on platforms having a version of python 2 where this works.

If you want, we could limit the change to

```
#!/usr/bin/env python3

# Many versions of python2 have poor SSL support and therefore, while the code is intended to
# be compatible with both python2 and python3, you may have to upgrade your SSL libraries and
# your python2 installation for this script to work.
```

But I do think we need to add a disclaimer of some sort if we still give the appearance of supporting python2 and python3.

Curious: Is there a strong reason you don't want to require python3 to run the submit script?

**Comment by austrin** [comment]
Also the official request docs claim that 2.7.9 should be sufficient: http://docs.python-requests.org/en/master/community/faq/ (bottom of page).  Are you sure that the issue you have is with SNI, or might it possibly be something else?

**Comment by mikaelgoldmann** [comment]
On Friday, 8 April 2016, austrin notifications@github.com wrote:

> Also the official request docs claim that 2.7.9 should be sufficient:
> http://docs.python-requests.org/en/master/community/faq/ (bottom of
> page). Are you sure that the issue you have is with SNI, or might it
> possibly be something else?

I'm sure it's SSL related. Does it work for you?

**Comment by mikaelgoldmann** [comment]
@pehrsoderman @niemela Didn't we have some similar issue with the people using the API? I think Pehr made som change on cloudflare to make it work. Am I misremembering? If not, was that change something we want to live with in the long term?

**Comment by pehrsoderman** [comment]
I remember turning off the application firewall in cloudflare, but I don't remember the exact issue that caused it.

**Comment by mikaelgoldmann** [comment]
Are we happy with it being off?

**Comment by pehrsoderman** [comment]
I would prefer to have it turned on, as it provides some basic protection against XSS and SQL injection.

**Comment by austrin** [comment]
> I would prefer to have it turned on, as it provides some basic protection against XSS and SQL injection. 

Could you turn it on?  I would like to do some testing.

**Comment by pehrsoderman** [comment]
It's on again. Feel free to test!

**Comment by austrin** [comment]
@mikaelgoldmann works in Python 2 on Ubuntu 14.04 for me.  Can you still reproduce it (and if so, on what system(s))?

**Comment by austrin** [comment]
> I can't. Let's close this and re-open if it happens again or if someone
> complains.

OK, but perhaps the second and third commits should still be salvaged?

**Pull request closed without merging**
