### PR TITLE
Show judgement after submitting

### PR DESCRIPTION
**Pull request by tyilo**
See https://asciinema.org/a/m5TONa3nz1vPeeP0hVIMvKsIl

### CODE REVIEW

**Review by niemela — APPROVED** [review]
👍

**Comment by tyilo** [comment]
Maybe kattis could provide a better api, so that we don't have to parse `row_html` to get the number of testcases has been checked and `feedback_html` to get the compiler error.
Instead it would be better if kattis directly provided:
- `total_testcases`
- `feedback_text`
- (`status_text` so we don't need `_STATUS_MAP`)

**Comment by tyilo** [comment]
Ping :)

**Comment by enikko** [comment]
Would be lovely to see this in the official code. Any reasons to why it has not been merged yet?

**Comment by niemela** [comment]
> Would be lovely to see this in the official code. Any reasons to why it has not been merged yet?

No good reason, no :(.

Merging now.

**Pull request merged**
